[package]
name = "pygisO3"
version = "0.1.0"
authors = ["cvonsteg <cvonstegmann@gmail.com>"]
edition = "2018"

[lib]
name = "gis"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.10.0"
features = ["extension-module"]
